databases:
  - name: webscraper
    databaseName: webscraper
    user: webscraper

services:
  - type: web
    name: webscraper
    plan: starter
    region: oregon
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.wsgi:application"
    autoDeploy: false
    envVars:
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: webscraper
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
